version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: daet-backend
    ports:
      - "8000:8000"
    env_file: .env
    volumes:
      - ./backend/reports:/app/backend/reports
      - ./backend/ai_cache:/app/backend/ai_cache

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
    image: daet-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
